#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 18 13:38:00 2019

@author: benjamin
"""

import numpy as np
import pandas as pd
import pandas_profiling

df=pd.DataFrame(
    np.random.rand(100, 5),
    columns=['a', 'b', 'c', 'd', 'e']
)